export enum IpcChannel {
  TRANSCRIBE = 'transcribe',
  TRANSCRIPTION_COMPLETE = 'transcription-complete',
  TRANSCRIPTION_STATUS = 'transcription-status',
  TOGGLE_RECORDING = 'toggle-recording',
  GET_SETTINGS = 'get-settings',
  UPDATE_SETTINGS = 'update-settings',
  GET_HISTORY = 'get-history',
  CLEAR_HISTORY = 'clear-history',
  COPY_TO_CLIPBOARD = 'copy-to-clipboard',
  DOWNLOAD_MODEL = 'download-model',
  DOWNLOAD_PROGRESS = 'download-progress',
  WIDGET_POSITION_SAVE = 'widget-position-save',
  WIDGET_POSITION_LOAD = 'widget-position-load',
  ONBOARDING_COMPLETE = 'onboarding-complete',
  IS_ONBOARDING_DONE = 'is-onboarding-done',
  OPEN_SETTINGS = 'open-settings',
  QUIT_APP = 'quit-app',
}
